log_level: TRACE
auth_secret: your-secret-key-here
dedup_mode: FAST
server_host: localhost
server_port: 8080
pre_process_quality_stack: true
threading:
  max_processing_threads: 8
  max_scan_threads: 4
  http_server_threads: auto
  database_threads: 2
scan_interval_seconds: 300
duplicate_linker_check_interval: 60
processing:
  batch_size: 100
categories:
  images:
    jpg: true
    jpeg: true
    png: true
    bmp: true
    gif: true
    tiff: true
    webp: true
    jp2: true
    ppm: true
    pgm: true
    pbm: true
    pnm: true
    exr: true
    hdr: true
  video:
    mp4: true
    avi: true
    mov: true
    mkv: true
    wmv: true
    flv: true
    webm: true
    m4v: true
    mpg: true
    mpeg: true
    ts: true
    mts: true
    m2ts: true
    ogv: true
  audio:
    mp3: true
    wav: true
    flac: true
    ogg: true
    m4a: true
    aac: true
    opus: true
    wma: true
    aiff: true
    alac: true
    amr: true
    au: true
  images_raw:
    cr2: true
    nef: true
    arw: true
    dng: true
    raf: true
    rw2: true
    orf: true
    pef: true
    srw: true
    kdc: true
    dcr: true
    mos: true
    mrw: true
    raw: true
    bay: true
    3fr: true
    fff: true
    mef: true
    iiq: true
    rwz: true
    nrw: true
    rwl: true
video_processing:
  FAST:
    skip_duration_seconds: 2
    frames_per_skip: 2
    skip_count: 5
  BALANCED:
    skip_duration_seconds: 1
    frames_per_skip: 2
    skip_count: 8
  QUALITY:
    skip_duration_seconds: 1
    frames_per_skip: 3
    skip_count: 12
database:
  retry:
    max_attempts: 3
    backoff_base_ms: 100
    max_backoff_ms: 1000
  timeout:
    busy_timeout_ms: 30000
    operation_timeout_ms: 60000
