# Configuration for Dedup Server
# 
# dedup_mode: enum ["FAST", "BALANCED", "QUALITY"]
#   - FAST: Fast processing with basic deduplication
#   - BALANCED: Balanced processing with moderate accuracy  
#   - QUALITY: High-quality processing with maximum accuracy
#
# log_level: enum ["TRACE", "DEBUG", "INFO", "WARN", "ERROR"]
#   - Controls overall logging verbosity
#   - TRACE: Most verbose, shows all operations
#   - DEBUG: Detailed debugging information
#   - INFO: General information and status updates
#   - WARN: Only warnings and errors (recommended for production)
#   - ERROR: Only error messages
log_level: "WARN"

# Processing verbosity: controls detailed logging during file processing
# - "MINIMAL": Only filename and mode (recommended for production)
# - "NORMAL": Includes processing details and success confirmations
# - "VERBOSE": All processing details including algorithm specifics
processing_verbosity: "MINIMAL"

# server_port: integer (1-65535)
#   - HTTP server port number
#
# server_host: string
#   - HTTP server host address
#
# auth_secret: string
#   - JWT authentication secret key
auth_secret: "your-secret-key-here"
dedup_mode: "BALANCED"
server_host: "localhost"
server_port: 8080

# Quality stack configuration
pre_process_quality_stack: true

# Thread pool configuration
threading:
  # Maximum number of threads for media processing operations
  max_processing_threads: 8
  # Maximum number of threads for file scanning operations
  max_scan_threads: 4
  # HTTP server thread pool (auto = hardware_concurrency - 1, or specify number)
  http_server_threads: "auto"
  # Database access queue threads (for concurrent database operations)
  database_threads: 2

# Scan intervals
scan_interval_seconds: 300        # How often to scan directories (5 minutes)
processing_interval_seconds: 10   # How often to process files (10 seconds)

# Processing batch size
processing:
  batch_size: 100

# Categories: images, video, audio, and images_raw (require transcoding)
categories:
  images:
    jpg: true
    jpeg: true
    png: true
    bmp: true
    gif: true
    tiff: true
    webp: true
    jp2: true
    ppm: true
    pgm: true
    pbm: true
    pnm: true
    exr: true
    hdr: true
  video:
    mp4: true
    avi: true
    mov: true
    mkv: true
    wmv: true
    flv: true
    webm: true
    m4v: true
    mpg: true
    mpeg: true
    ts: true
    mts: true
    m2ts: true
    ogv: true
  audio:
    mp3: true
    wav: true
    flac: true
    ogg: true
    m4a: true
    aac: true
    opus: true
    wma: true
    aiff: true
    alac: true
    amr: true
    au: true
  images_raw:
    # Raw camera formats - LibRaw supported
    cr2: true
    nef: true
    arw: true
    dng: true
    raf: true
    rw2: true
    orf: true
    pef: true
    srw: true
    kdc: true
    dcr: true
    mos: true
    mrw: true
    raw: true
    bay: true
    3fr: true
    fff: true
    mef: true
    iiq: true
    rwz: true
    nrw: true
    rwl: true
    # Note: r3d (Red RAW), dcm, dicom (DICOM) removed - not supported by LibRaw

# Video processing settings for each quality mode
video_processing:
  FAST:
    # Number of seconds to skip between frame groups
    skip_duration_seconds: 2
    # Number of frames to extract at each skip point
    frames_per_skip: 2
    # Number of skip points (template length)
    skip_count: 5
  BALANCED:
    skip_duration_seconds: 1
    frames_per_skip: 2
    skip_count: 8
  QUALITY:
    skip_duration_seconds: 1
    frames_per_skip: 3
    skip_count: 12
